-- Seed events table with data from CSV
-- Run this after the table structure migration is complete

-- Clear any existing events first (optional)
-- DELETE FROM events;

INSERT INTO events (
  name,
  description,
  event_type,
  min_team_size,
  max_team_size,
  rules,
  rounds,
  price,
  category,
  incharge_name1,
  incharge_phone1,
  incharge_name2,
  incharge_phone2,
  participant_limit,
  venue,
  event_date,
  time_slot
) VALUES 
-- Technical Events
(
  'Code Arena',
  'The Secret Levels is a thrilling, multi-level coding challenge where participants discover rounds only as they progress. Each level comes with a unique coding twist, testing debugging, logic building, problem-solving speed, and teamwork. Difficulty escalates with every round, ensuring only the sharpest coders survive till the end.',
  'team',
  2,
  2,
  '<ul><li>Team of 2 participants</li><li>Laptop compulsory</li><li>Online compilers/editors provided</li><li>Allowed Languages: C, C++, Java, Python</li><li>Use of AI tools (ChatGPT, Copilot, etc.) is strictly prohibited</li><li>Rounds will be revealed on the spot</li><li>Time limits for each round will be announced before start</li><li>Evaluation Criteria: correctness, efficiency, speed, teamwork</li></ul>',
  '<ul><li>Round Announcements: Each challenge will be revealed on the spot with its own time limit</li><li><strong>Challenge Format:</strong><ul><li>Multiple rounds with varying challenges</li><li>Each round tests different programming skills</li><li>Time limits announced before each round begins</li></ul></li></ul>',
  100,
  'technical',
  'Sakthidharan M A',
  '9445604603',
  'Harini Anand',
  '8667716119',
  20,
  'Computer Lab',
  '2025-09-15',
  'morning'
),
(
  'Pitch Roulette',
  'The 90-Minute Unicorn is a high-speed innovation battle where teams discover their startup''s domain only at the start. Each random spin delivers a unique challenge, testing on-the-spot ideation, rapid technical design, creative problem-solving, and persuasive storytelling.',
  'team',
  2,
  4,
  '<ul><li>Team Size: 2-4 members per team</li><li>Equipment: Laptop with presentation software compulsory</li><li>AI Policy: Use of AI tools completely allowed and encouraged</li><li>Time Limits: A strict 90-minute limit for ideation and deck creation</li><li>Evaluation Criteria: Creativity, Technical Explanation, Presentation, Problem-Solution Fit</li></ul>',
  '<ul><li><strong>The Domain Draw</strong><ul><li>Teams assigned domain through randomized process</li><li>Domains span technical, social, niche, and abstract themes</li></ul></li><li><strong>Ideation Phase (90 Minutes)</strong><ul><li>Strict 90-minute timer for ideation and deck creation</li><li>AI tools allowed but must be disclosed</li></ul></li><li><strong>Pitch Presentation</strong><ul><li>3 minutes to present + 3-minute Q&A</li></ul></li></ul>',
  200,
  'technical',
  'Dhana Anjana S',
  '8939670208',
  'Sree Simhan',
  '7358651861',
  20,
  'Seminar Hall',
  '2025-09-15',
  'afternoon'
),
(
  'Logic Break',
  'A three-round progressive challenge including code debugging, clue decoding, Hangman puzzles, and a final integrated team puzzle. Requires logical thinking and teamwork.',
  'team',
  1,
  2,
  '<ul><li>Teams may consist of 1 or 2 participants</li><li>Paper and pen will be provided for rough work</li><li>Speed and accuracy determine progress in each round</li><li>Any form of malpractice leads to immediate disqualification</li></ul>',
  '<ul><li><strong>Round 1 – Decode & Debug</strong><ul><li>Debug buggy program to convert binary string into words</li><li>Top 10 teams qualify</li></ul></li><li><strong>Round 2 – Debug, Hangman & Treasure Hunt</strong><ul><li>Debug program, solve Hangman, complete treasure hunt</li><li>Top 5 teams qualify</li></ul></li><li><strong>Round 3 – The Final Challenge</strong><ul><li>Use all collected clues to solve final integrated puzzle</li></ul></li></ul>',
  100,
  'technical',
  'Sabarish Sha Kumar',
  '9884017774',
  'Siddarth Sathish Iyer',
  '9345947847',
  20,
  'Computer Lab',
  '2025-09-16',
  'morning'
),
(
  'Code Gambit',
  'A 3-round coding event combining debugging, coding logic, and strategy. Focuses on testing speed, problem-solving accuracy, and tactical thinking.',
  'team',
  2,
  3,
  '<ul><li>Each team must bring one laptop</li><li>Allowed programming languages: C, C++, Java, Python</li><li>Use of AI tools strictly prohibited</li><li>Judges decisions will be final and binding</li></ul>',
  '<ul><li><strong>Round 1: Syntax Sprint</strong><ul><li>15 multiple-choice questions on buggy code</li><li>Top 10 teams qualify</li></ul></li><li><strong>Round 2: Debug Detective</strong><ul><li>3 programming tasks with intentional bugs</li><li>Top 4 teams qualify</li></ul></li><li><strong>Round 3: Fix-It Faceoff</strong><ul><li>Tic-Tac-Toe styled debugging showdown</li></ul></li></ul>',
  150,
  'technical',
  'Gowsi S M',
  '9789809707',
  'Akshaya',
  '7200414682',
  50,
  'Computer Lab',
  '2025-09-16',
  'afternoon'
),
(
  'Paper Presentation',
  'A comprehensive technical paper presentation competition featuring abstract screening, presentation rounds, and viva voce. Teams present research papers from all technical domains following IEEE format standards.',
  'team',
  2,
  5,
  '<ul><li>Topics from all technical domains are accepted</li><li>Abstract and presentation must be submitted prior to the event</li><li>Paper must follow IEEE format</li><li>Viva voce will be conducted after the presentation</li></ul>',
  '<ul><li><strong>Abstract Submission & Screening</strong><ul><li>Teams submit abstracts for shortlisting</li></ul></li><li><strong>Presentation Round</strong><ul><li>Shortlisted teams present their paper (12–15 slides)</li></ul></li><li><strong>Viva Voce</strong><ul><li>Q&A based on presentation</li></ul></li></ul>',
  250,
  'technical',
  'Chandrasekar',
  '9037183292',
  'Harshitha',
  '8248740958',
  30,
  'Seminar Hall',
  '2025-09-17',
  'morning'
),
(
  'Pixel Perfect (UI/UX Challenge)',
  'A three-round UI/UX design challenge blending debugging, clue solving, and rapid prototyping. Ideal for design enthusiasts, product thinkers, and creative coders.',
  'team',
  2,
  3,
  '<ul><li>Team size: 2–3 members</li><li>Laptop required</li><li>Internet and Figma Education access provided</li><li>AI/generative tools prohibited</li><li>Only licensed/free assets allowed</li></ul>',
  '<ul><li><strong>Round 1: Pixel Probe</strong><ul><li>Debug UI components and fix design issues</li><li>Top 10 teams qualify</li></ul></li><li><strong>Round 2: Design Quest</strong><ul><li>Mini audit, design hangman, treasure hunt</li><li>Top 5 teams qualify</li></ul></li><li><strong>Round 3: Pixel Forge</strong><ul><li>Design end-to-end solution in Figma</li></ul></li></ul>',
  150,
  'technical',
  'Praveen Kumar',
  '7358505437',
  'Mohin Kumar',
  '9150349047',
  20,
  'Design Lab',
  '2025-09-17',
  'afternoon'
),
(
  'Go Gemini',
  'Go Gemini challenges participants to leverage Gemini''s capabilities to build innovative solutions through creativity and rapid prototyping.',
  'team',
  2,
  2,
  '<ul><li>Team Size: 2 members per team</li><li>Laptop Compulsory</li><li>Any programming language allowed</li><li>AI tools including Gemini allowed and encouraged</li></ul>',
  'Single round competition with AI tools integration',
  100,
  'technical',
  'Tejasvi',
  '9884369156',
  'Tharun',
  '7358211813',
  25,
  'Computer Lab',
  '2025-09-18',
  'morning'
),
(
  'SQL Code OFF',
  'A three-round SQL and DBMS challenge focused on query writing, logic, and schema design. Tests database fluency, optimization, and modeling skills.',
  'team',
  1,
  2,
  '<ul><li>Team size: 1–2 members</li><li>Laptop required</li><li>Internet and SQL sandbox access provided</li><li>AI/generative tools prohibited</li><li>Only original work allowed</li></ul>',
  '<ul><li><strong>Round 1: Query Quickfire</strong><ul><li>SQL challenges covering basic operations</li><li>Top 10 teams qualify</li></ul></li><li><strong>Round 2: Logic Lab</strong><ul><li>Scenario-based queries and error hunting</li><li>Top 5 teams qualify</li></ul></li><li><strong>Round 3: Schema Forge</strong><ul><li>Design normalized database schema</li></ul></li></ul>',
  100,
  'technical',
  'Soban Shankar',
  '9444389781',
  'Tejashree',
  '8825476548',
  20,
  'Computer Lab',
  '2025-09-18',
  'afternoon'
),
(
  'No Code Arcade',
  'A game development challenge using no-code editors to create playable games with provided assets and themes.',
  'team',
  1,
  2,
  '<ul><li>Team size: 1–2 members</li><li>Laptop required</li><li>Only designated no-code editor and provided assets allowed</li><li>External code and AI tools prohibited</li></ul>',
  '<ul><li><strong>Build & Play Round</strong><ul><li>Create playable game with provided assets</li><li>Must include core mechanic, 3-5 screens, clear objective</li><li>Judged on playability and creativity</li></ul></li></ul>',
  100,
  'technical',
  'Event Coordinator',
  '9876543210',
  'Assistant Coordinator',
  '9876543211',
  20,
  'Computer Lab',
  '2025-09-19',
  'morning'
),
(
  'Front End AI Sprint',
  'Encourages creative problem solving in practical front-end development and promotes awareness of AI-assisted coding tools.',
  'team',
  2,
  3,
  '<ul><li>Teams must bring laptops with required software</li><li>AI tools strongly encouraged</li><li>Online resources allowed for inspiration</li><li>Original solutions created during event required</li></ul>',
  '<ul><li><strong>Round 1: Quick Front-End Challenge (20 Minutes)</strong><ul><li>Test speed, accuracy, and technical fluency</li></ul></li><li><strong>Round 2: Business Website Challenge (30 Minutes)</strong><ul><li>Build functional business website</li><li>Bonus points for AI-driven features</li></ul></li></ul>',
  150,
  'technical',
  'Sayanth',
  '9092992203',
  'Priyanjana',
  '9498027683',
  20,
  'Computer Lab',
  '2025-09-19',
  'afternoon'
),
(
  'Battle of the Bash - A Linux CLI Challenge',
  'A hands-on cybersecurity and system administration competition designed exclusively for freshers to showcase their command-line skills in Linux.',
  'solo',
  1,
  1,
  '<ul><li>Competition designed exclusively for freshers</li><li>All tasks must be solved using pure Linux commands only</li><li>Each task hides a unique flag</li><li>Scoring based on accuracy, speed, and efficiency</li></ul>',
  '<ul><li><strong>Stage 1 (Basics)</strong><ul><li>Simple navigation and search operations</li></ul></li><li><strong>Stage 2 (Intermediate)</strong><ul><li>Data manipulation, log analysis, compression puzzles</li></ul></li><li><strong>Stage 3 (Advanced)</strong><ul><li>Forensics, process debugging, multi-step decoding</li></ul></li></ul>',
  50,
  'technical',
  'Someshwar',
  '9940174942',
  'Assistant',
  '9876543212',
  40,
  'Computer Lab',
  '2025-09-20',
  'morning'
),
(
  'Tech Adventure Challenge',
  'A multi-round tech challenge combining Wi-Fi network discovery, coding puzzles, cryptography, and treasure hunting.',
  'team',
  2,
  4,
  '<ul><li>Team Size: 2–4 members</li><li>Teams must complete all rounds sequentially</li><li>Speed matters in coding rounds</li><li>All collected hints needed for final round</li></ul>',
  '<ul><li><strong>Round 1 – Wi-Fi Clue Hunt</strong><ul><li>Find hidden Wi-Fi hotspots with tech puzzles</li></ul></li><li><strong>Round 2 – Code Puzzle Sprint</strong><ul><li>Crack coding & logic problems</li></ul></li><li><strong>Round 3 – Cryptic Quest</strong><ul><li>Decode ciphers, QR codes, and riddles</li></ul></li><li><strong>Round 4 – Tech Treasure Finale</strong><ul><li>Use all hints to unlock final puzzle</li></ul></li></ul>',
  200,
  'technical',
  'Gladwinn',
  '9444291922',
  'Sahaana',
  '9444243492',
  35,
  'Multiple Venues',
  '2025-09-20',
  'afternoon'
),

-- No Code Events
(
  'Ghibli Sketch-Off',
  'Bring Studio Ghibli''s magical worlds to life with your artistic touch. A fun sketching challenge for anime and art lovers.',
  'solo',
  1,
  1,
  '<ul><li>Individual participation only</li><li>A3 sheet provided; bring own art materials</li><li>Any medium allowed</li><li>Artwork must resemble given image in own style</li><li>Tracing or copying prohibited</li></ul>',
  '<ul><li><strong>Sketching Round</strong><ul><li>Image projected on screen</li><li>First appears in Ghibli-style for 2 minutes</li><li>Original image then displayed</li><li>Recreate using provided materials</li></ul></li></ul>',
  50,
  'no_code',
  'Anupama',
  '7845872154',
  'Mahalakshmi',
  '9363023735',
  30,
  'Art Room',
  '2025-09-21',
  'morning'
),
(
  'Byte N Guess',
  'Crack the code of fun. Decode hints, identify tech terms, and guess the answers to win.',
  'team',
  2,
  3,
  '<ul><li>Teams of 2 or 3 participants</li><li>Time limits must be strictly followed</li><li>Highest cumulative score wins</li><li>Any malpractice leads to disqualification</li></ul>',
  '<ul><li><strong>Round 1 – Spot the Real Logo</strong><ul><li>Buzzer round with logo identification</li><li>Top 10 teams qualify</li></ul></li><li><strong>Round 2 – Image Connection</strong><ul><li>Connect images to brands/companies</li><li>Top 5 teams qualify</li></ul></li><li><strong>Round 3 – Draw & Guess</strong><ul><li>Draw brand/logo for team to guess</li></ul></li></ul>',
  150,
  'no_code',
  'Tasha Ann Titus',
  '9003220727',
  'Madhumitha Vijay',
  '9487466531',
  15,
  'Auditorium',
  '2025-09-21',
  'afternoon'
),
(
  'Prompt Wars',
  'Test your creativity by crafting the perfect AI prompts and watch your imagination come alive in generated outputs.',
  'team',
  2,
  3,
  '<ul><li>Teams of 2–3 participants</li><li>Internet access provided for prompt generation only</li><li>External prompt libraries prohibited</li><li>Creativity and originality determine advancement</li></ul>',
  '<ul><li><strong>Round 1 – Spot the Fake</strong><ul><li>Identify AI-generated vs real images</li><li>Top 10 teams qualify</li></ul></li><li><strong>Round 2 – Word Trap</strong><ul><li>Create prompts with constraints</li><li>Top 5 teams qualify</li></ul></li><li><strong>Round 3 – Reverse Prompt Gambit</strong><ul><li>Reverse-engineer prompts from images</li></ul></li></ul>',
  150,
  'no_code',
  'Hemanthkumar',
  '9123563779',
  'Dhivya',
  '9176540803',
  20,
  'Computer Lab',
  '2025-09-22',
  'morning'
),
(
  'Brain Sprint',
  'A fast-paced memory challenge designed to test how sharp your mind really is across three unique rounds.',
  'team',
  3,
  3,
  '<ul><li>Three rounds of memory challenges</li><li>Pay close attention during displays</li><li>External aids strictly prohibited</li><li>Responses must be given within time limits</li></ul>',
  '<ul><li><strong>Round 1: Flip & Find</strong><ul><li>Match hidden pairs by flipping memory cards</li></ul></li><li><strong>Round 2: Word Relay</strong><ul><li>Build chain of words, repeat and add new ones</li></ul></li><li><strong>Round 3: Picture Recall</strong><ul><li>Observe image for 2 minutes, then recall objects</li></ul></li></ul>',
  150,
  'no_code',
  'Baleshwar',
  '9566044274',
  'Jayashree',
  '8610567763',
  20,
  'Classroom',
  '2025-09-22',
  'afternoon'
),

-- Online Events
(
  'Photography',
  'Capture the perfect shot that speaks louder than words. Show your perspective through the lens and stand out.',
  'solo',
  1,
  1,
  '<ul><li>Submit one original photograph reflecting theme "World in Motion"</li><li>Digital format (JPEG/PNG) required</li><li>Only basic color correction allowed</li><li>Include title and short description</li></ul>',
  '<ul><li><strong>Online Photography Contest</strong><ul><li>Submit via provided link before deadline</li><li>Shortlisted photos displayed online</li><li>Winners announced on official platform</li></ul></li></ul>',
  50,
  'online',
  'Adithya Kiran',
  '7338729586',
  'Vishal Krishna',
  '9150426322',
  100,
  'Online Platform',
  '2025-09-23',
  'both'
),
(
  'Content Creation',
  'A creative video-making challenge where participants design a short informational video based on a given theme.',
  'solo',
  1,
  1,
  '<ul><li>Solo participation only</li><li>Create 1–2 minute informational video</li><li>Must use storytelling, hooks, and creativity</li><li>Original work only with plagiarism check</li></ul>',
  '<ul><li><strong>Single Round Video Creation</strong><ul><li>Theme/topic given at start</li><li>Video should be informational and engaging</li><li>Submit within deadline</li></ul></li></ul>',
  50,
  'online',
  'Jaisurya',
  '9677155266',
  'Monish Kumar',
  '9940523740',
  25,
  'Online Platform',
  '2025-09-24',
  'both'
),
(
  'Chess',
  'Outthink, outmaneuver, and raise the stakes—every move counts in this battle of minds for a cause.',
  'solo',
  1,
  1,
  '<ul><li>Solo participation only</li><li>Fair play strictly monitored</li><li>No external assistance or engines allowed</li><li>Time control rules are final</li></ul>',
  '<ul><li><strong>Round 1 – Lightning Knockout</strong><ul><li>5-minute blitz matches</li><li>Top 24 qualify</li></ul></li><li><strong>Round 2 – Swiss Rapid</strong><ul><li>10|0 Rapid format</li><li>Top 12 qualify</li></ul></li><li><strong>Round 3 – Swiss Blitz</strong><ul><li>5|5 Blitz format</li><li>Top 6 qualify</li></ul></li><li><strong>Round 4 – Semi-Finals</strong><ul><li>10|5 Rapid format</li><li>Top 2 qualify</li></ul></li><li><strong>Round 5 – Grand Final</strong><ul><li>Best-of-2 games</li></ul></li></ul>',
  50,
  'online',
  'Tarun',
  '8444525879',
  'Rubika',
  '8110947404',
  64,
  'Online Platform',
  '2025-09-25',
  'both'
),
(
  'BGMI',
  'Drop in, gear up, and fight for glory. Your squad''s skills fuel the mission and the movement.',
  'team',
  1,
  4,
  '<ul><li>No cheating, hacks, or third-party software</li><li>No teaming or collusion between squads</li><li>Only registered players allowed</li><li>No toxic behavior or harassment</li></ul>',
  '<ul><li><strong>Match Start & Gameplay</strong><ul><li>Standard classic squad match on Erangel map</li><li>Objective: survive until the end</li><li>Match duration: 25-30 minutes</li></ul></li></ul>',
  50,
  'online',
  'Agnel Anjalo',
  '9360458832',
  'Prasanth',
  '7708190032',
  32,
  'Online Platform',
  '2025-09-26',
  'afternoon'
),
(
  'FreeFire',
  'A competitive battle royale tournament featuring Full Map (Bermuda) and Clash Squad modes with progressive elimination stages.',
  'team',
  1,
  4,
  '<ul><li>No VPN usage</li><li>PC players not allowed</li><li>No bugs or hacks</li><li>Gun properties and character skills OFF</li><li>Join within 5 minutes of receiving lobby details</li></ul>',
  '<ul><li><strong>First Round</strong><ul><li>4 groups play Full Map</li><li>Top 4 teams per group qualify</li></ul></li><li><strong>Second Round</strong><ul><li>Merged groups play Full Map</li><li>Top 2 teams per match qualify</li></ul></li><li><strong>Third Round</strong><ul><li>Clash Squad format</li><li>Winners qualify for finals</li></ul></li><li><strong>Final Round</strong><ul><li>Clash Squad championship match</li></ul></li></ul>',
  50,
  'online',
  'Abinithin',
  '8189933998',
  'Ajay Kiran',
  '9360711920',
  48,
  'Online Platform',
  '2025-09-27',
  'afternoon'
),

-- Playground Events
(
  'Futsal',
  'Indoor football tournament with fast-paced gameplay and modified rules for smaller teams.',
  'team',
  5,
  7,
  '<ul><li>Teams must have 5-7 players</li><li>Standard futsal rules apply</li><li>Match duration: 20 minutes (10 minutes each half)</li><li>Substitutions allowed during play</li><li>Fair play is mandatory</li></ul>',
  '<ul><li><strong>Group Stage</strong><ul><li>Teams divided into groups</li><li>Round robin format within groups</li></ul></li><li><strong>Knockout Stage</strong><ul><li>Top teams from each group advance</li><li>Single elimination format</li></ul></li></ul>',
  100,
  'playground',
  'Risto Darrel',
  '9360041431',
  'Shaktidhar',
  '7338863538',
  16,
  'Football Ground',
  '2025-09-28',
  'morning'
),
(
  'Box Cricket',
  'Cricket tournament in limited space with modified rules for exciting gameplay.',
  'team',
  6,
  8,
  '<ul><li>Teams must have 6-8 players</li><li>6 overs per side</li><li>Boundaries and rules adapted for box cricket</li><li>All players must bowl at least one over</li><li>Fair play and sportsmanship required</li></ul>',
  '<ul><li><strong>League Stage</strong><ul><li>Teams play in round robin format</li><li>Points awarded for wins and ties</li></ul></li><li><strong>Finals</strong><ul><li>Top teams compete in finals</li><li>Winner decided by best performance</li></ul></li></ul>',
  150,
  'playground',
  'Sujay Shrinivash',
  '7200024507',
  'Sanjay Mohan',
  '9840071820',
  12,
  'Cricket Ground',
  '2025-09-28',
  'afternoon'
),
(
  'Badminton',
  'Badminton tournament with singles and doubles matches in knockout format.',
  'team',
  1,
  2,
  '<ul><li>Singles and doubles categories</li><li>Standard badminton rules</li><li>Best of 3 sets format</li><li>Knockout tournament structure</li><li>Players must bring own rackets</li></ul>',
  '<ul><li><strong>Singles Tournament</strong><ul><li>Individual knockout format</li><li>Best of 3 sets</li></ul></li><li><strong>Doubles Tournament</strong><ul><li>Team of 2 players</li><li>Knockout format</li></ul></li></ul>',
  75,
  'playground',
  'Tarun',
  '9444525879',
  'Vishal',
  '7358473538',
  24,
  'Badminton Court',
  '2025-09-29',
  'morning'
);

-- Verify the data was inserted
SELECT COUNT(*) as total_events FROM events;
SELECT category, COUNT(*) as count_per_category FROM events GROUP BY category;
SELECT name, event_date, time_slot, venue FROM events ORDER BY event_date, time_slot;
